"""Foundry Local backend adapter.

Microsoft Foundry Local serves an OpenAI-compatible API. We treat it the
same way as Ollama: a shell wrapper that pipes responses through the
generic webhook.

If a future Foundry release ships native completion hooks, this adapter
can switch to that mechanism without changing the public webhook surface.
"""
from __future__ import annotations

import logging
import shlex
import shutil
from pathlib import Path

from claudible.hooks.backends.base import BackendAdapter, BackendStatus

log = logging.getLogger(__name__)

WRAPPER_NAME = "foundry-claudible"
WRAPPER_DIR = Path.home() / ".local" / "bin"


class FoundryAdapter(BackendAdapter):
    name = "foundry"
    label = "Foundry Local"

    def detect(self) -> bool:
        # Foundry CLI is "foundry" on disk; alternatively a service on
        # localhost:5273 by default.
        return shutil.which("foundry") is not None

    def install(self, *, host: str, port: int, token: str | None = None) -> None:
        WRAPPER_DIR.mkdir(parents=True, exist_ok=True)
        target = WRAPPER_DIR / WRAPPER_NAME
        target.write_text(_wrapper_script(host=host, port=port, token=token))
        target.chmod(0o755)
        log.info("Installed Foundry wrapper at %s", target)

    def uninstall(self) -> None:
        target = WRAPPER_DIR / WRAPPER_NAME
        if target.exists():
            target.unlink()
            log.info("Removed Foundry wrapper %s", target)

    def status(self) -> BackendStatus:
        target = WRAPPER_DIR / WRAPPER_NAME
        installed = target.exists()
        return BackendStatus(
            name=self.name,
            detected=self.detect(),
            installed=installed,
            details=str(target) if installed else "",
        )


def _wrapper_script(*, host: str, port: int, token: str | None) -> str:
    """Foundry CLI accepts the same wrapping pattern as ollama.

    All interpolated values are shell-quoted: the result is written
    executable into ~/.local/bin, so an unquoted value is an injection sink.
    """
    fire = shlex.quote(str(Path.home() / ".local" / "bin" / "claudible-hook-fire"))
    # NOTE: --token places the credential in argv, where `ps` can see it.
    token_arg = f"--token {shlex.quote(token)} " if token else ""
    return f"""#!/usr/bin/env bash
# Auto-generated by claudible. Wraps `foundry` and fires the generic webhook.
set -euo pipefail
TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
foundry "$@" | tee "$TMPFILE"
{fire} \\
    --tool foundry \\
    --file "$TMPFILE" \\
    --host {shlex.quote(host)} --port {int(port)} \\
    {token_arg}\\
    >/dev/null 2>&1 || true
"""
