"""Generic backend adapter for arbitrary CLI tools.

For tools that don't have a known hook mechanism, the user supplies a
process name (or path) and we install a wrapper that POSTs each completion
to the generic webhook. Identical semantics to ollama/foundry, but no
detection — the user owns this.
"""
from __future__ import annotations

import logging
from pathlib import Path

from claudible.hooks.backends.base import BackendAdapter, BackendStatus

log = logging.getLogger(__name__)

WRAPPER_DIR = Path.home() / ".local" / "bin"


class GenericAdapter(BackendAdapter):
    """Adapter for tools we don't have a dedicated module for.

    Parameterized by the wrapped command's name. Construct with
    ``GenericAdapter("my-tool")`` or via ``ADAPTERS['generic']("my-tool")``.
    """

    name = "generic"
    label = "Generic CLI tool"

    def __init__(self, command: str = "") -> None:
        self.command = command

    @property
    def wrapper_name(self) -> str:
        return f"{self.command}-claudible" if self.command else "tool-claudible"

    def detect(self) -> bool:
        # Caller knows whether the tool exists; we don't second-guess.
        return bool(self.command)

    def install(self, *, host: str, port: int, token: str | None = None) -> None:
        if not self.command:
            raise ValueError("GenericAdapter requires a command name")
        WRAPPER_DIR.mkdir(parents=True, exist_ok=True)
        target = WRAPPER_DIR / self.wrapper_name
        target.write_text(_wrapper_script(self.command, host=host, port=port, token=token))
        target.chmod(0o755)
        log.info("Installed wrapper for %s at %s", self.command, target)

    def uninstall(self) -> None:
        target = WRAPPER_DIR / self.wrapper_name
        if target.exists():
            target.unlink()
            log.info("Removed wrapper %s", target)

    def status(self) -> BackendStatus:
        target = WRAPPER_DIR / self.wrapper_name
        installed = target.exists()
        return BackendStatus(
            name=self.name,
            detected=self.detect(),
            installed=installed,
            details=str(target) if installed else "",
        )


def _wrapper_script(command: str, *, host: str, port: int, token: str | None) -> str:
    return f"""#!/usr/bin/env bash
# Auto-generated by claudible for `{command}`. Pipes output to the generic webhook.
set -euo pipefail
TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
{command} "$@" | tee "$TMPFILE"
{Path.home() / ".local" / "bin" / "claudible-hook-fire"} \\
    --tool {command} \\
    --file "$TMPFILE" \\
    --host {host} --port {port} \\
    {('--token ' + token) if token else ''} \\
    >/dev/null 2>&1 || true
"""
