"""Generic backend adapter for arbitrary CLI tools.

For tools that don't have a known hook mechanism, the user supplies a
process name (or path) and we install a wrapper that POSTs each completion
to the generic webhook. Identical semantics to ollama/foundry, but no
detection — the user owns this.

Quoting note
------------
Everything interpolated into the generated script is passed through
``shlex.quote``. The script is written executable into ``~/.local/bin``, so
an unquoted value would be a straight command-injection sink. The command
name is additionally validated as a bare name so it cannot traverse out of
the wrapper directory via the generated filename.
"""
from __future__ import annotations

import logging
import re
import shlex
from pathlib import Path

from claudible.hooks.backends.base import BackendAdapter, BackendStatus

log = logging.getLogger(__name__)

WRAPPER_DIR = Path.home() / ".local" / "bin"

#: A wrapped command must be a bare executable name — it becomes part of a
#: filename under WRAPPER_DIR, so "/" and ".." are rejected outright.
_COMMAND_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")


def _validate_command(command: str) -> str:
    if not _COMMAND_RE.match(command):
        raise ValueError(
            f"Invalid command name {command!r}: expected a bare executable name "
            "matching [A-Za-z0-9][A-Za-z0-9_.-]* (no paths, spaces, or shell characters)"
        )
    return command


class GenericAdapter(BackendAdapter):
    """Adapter for tools we don't have a dedicated module for.

    Parameterized by the wrapped command's name. Construct with
    ``GenericAdapter("my-tool")`` or via ``ADAPTERS['generic']("my-tool")``.
    """

    name = "generic"
    label = "Generic CLI tool"

    def __init__(self, command: str = "") -> None:
        self.command = _validate_command(command) if command else ""

    @property
    def wrapper_name(self) -> str:
        return f"{self.command}-claudible" if self.command else "tool-claudible"

    def detect(self) -> bool:
        # Caller knows whether the tool exists; we don't second-guess.
        return bool(self.command)

    def install(self, *, host: str, port: int, token: str | None = None) -> None:
        if not self.command:
            raise ValueError("GenericAdapter requires a command name")
        WRAPPER_DIR.mkdir(parents=True, exist_ok=True)
        target = WRAPPER_DIR / self.wrapper_name
        target.write_text(
            _wrapper_script(self.command, host=host, port=port, token=token)
        )
        target.chmod(0o755)
        log.info("Installed wrapper for %s at %s", self.command, target)

    def uninstall(self) -> None:
        target = WRAPPER_DIR / self.wrapper_name
        if target.exists():
            target.unlink()
            log.info("Removed wrapper %s", target)

    def status(self) -> BackendStatus:
        target = WRAPPER_DIR / self.wrapper_name
        installed = target.exists()
        return BackendStatus(
            name=self.name,
            detected=self.detect(),
            installed=installed,
            details=str(target) if installed else "",
        )


def _wrapper_script(command: str, *, host: str, port: int, token: str | None) -> str:
    command = _validate_command(command)
    fire = shlex.quote(str(Path.home() / ".local" / "bin" / "claudible-hook-fire"))
    # NOTE: --token places the credential in argv, where `ps` can see it.
    # Tracked separately; changing it requires a matching change in
    # claudible-hook-fire's argument contract.
    token_arg = f"--token {shlex.quote(token)} " if token else ""
    return f"""#!/usr/bin/env bash
# Auto-generated by claudible for `{command}`. Pipes output to the generic webhook.
set -euo pipefail
TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
{shlex.quote(command)} "$@" | tee "$TMPFILE"
{fire} \\
    --tool {shlex.quote(command)} \\
    --file "$TMPFILE" \\
    --host {shlex.quote(host)} --port {int(port)} \\
    {token_arg}\\
    >/dev/null 2>&1 || true
"""
