"""Ollama backend adapter.

Ollama serves an OpenAI-compatible chat API at ``http://localhost:11434/v1``.
The integration here is a thin shell wrapper: callers run ``ollama-claudible
<args>`` instead of ``ollama <args>``; the wrapper pipes Ollama's final
response through the generic webhook.

This keeps Ollama itself untouched and works for any user, whether they
invoke Ollama from a terminal, a script, or a downstream tool that respects
``$OLLAMA_BIN``.
"""
from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path

from claudible.hooks.backends.base import BackendAdapter, BackendStatus

log = logging.getLogger(__name__)

WRAPPER_NAME = "ollama-claudible"
WRAPPER_DIR = Path.home() / ".local" / "bin"


class OllamaAdapter(BackendAdapter):
    name = "ollama"
    label = "Ollama (OpenAI-compatible local server)"

    def detect(self) -> bool:
        return shutil.which("ollama") is not None

    def install(self, *, host: str, port: int, token: str | None = None) -> None:
        WRAPPER_DIR.mkdir(parents=True, exist_ok=True)
        target = WRAPPER_DIR / WRAPPER_NAME
        wrapper = _wrapper_script(host=host, port=port, token=token)
        target.write_text(wrapper)
        target.chmod(0o755)
        log.info("Installed Ollama wrapper at %s", target)

    def uninstall(self) -> None:
        target = WRAPPER_DIR / WRAPPER_NAME
        if target.exists():
            target.unlink()
            log.info("Removed Ollama wrapper %s", target)

    def status(self) -> BackendStatus:
        target = WRAPPER_DIR / WRAPPER_NAME
        installed = target.exists()
        return BackendStatus(
            name=self.name,
            detected=self.detect(),
            installed=installed,
            details=str(target) if installed else "",
        )


def _wrapper_script(*, host: str, port: int, token: str | None) -> str:
    """Return a POSIX shell script that proxies Ollama and fires the webhook.

    Note: kept dependency-free (no curl/jq required) to maximize portability;
    we rely on /usr/bin/env python3 which Ollama users will already have.
    """
    auth_header = (
        f'        "Authorization": "Bearer {token}",\n' if token else ""
    )
    return f"""#!/usr/bin/env bash
# Auto-generated by claudible. Wraps `ollama` and fires the generic webhook
# at the end of each completion so the response is spoken aloud.
set -euo pipefail
TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT
ollama "$@" | tee "$TMPFILE"
# Fire-and-forget POST; we don't want hook failures to disrupt ollama.
{Path.home() / ".local" / "bin" / "claudible-hook-fire"} \\
    --tool ollama \\
    --file "$TMPFILE" \\
    --host {host} --port {port} \\
    {('--token ' + token) if token else ''} \\
    >/dev/null 2>&1 || true
"""
