"""Generate the nerd-dictation callback script.

nerd-dictation auto-loads ~/.config/nerd-dictation/nerd-dictation.py if it exists.
This module generates that script from the current config, embedding keyword mappings
and option-selection voice commands directly (no claudible imports at runtime).
"""

from __future__ import annotations

import logging
from pathlib import Path

from claudible.config import Config

log = logging.getLogger(__name__)

CALLBACK_DIR = Path.home() / ".config" / "nerd-dictation"
CALLBACK_FILE = CALLBACK_DIR / "nerd-dictation.py"

# Template for the generated callback script.
_TEMPLATE = '''\
"""Auto-generated by claudible. Do not edit manually."""

import json
import os
import subprocess
import time

# Voice keyword → X11 keystroke mappings
KEYWORDS = {keywords_dict}

# Number word → digit for option selection
NUMBER_WORDS = {number_words_dict}

# Prefixes that trigger option selection (e.g. "select 2", "option three")
OPTION_PREFIXES = ("select", "option", "number", "choose", "pick")

# Wake word configuration
WAKEWORD_ENABLED = {wakeword_enabled}
TRIGGER_WORDS = {trigger_words_dict}
DEACTIVATION_TIMEOUT = {deactivation_timeout}
WAKEWORD_STATE_PATH = {wakeword_state_path}

# Window lock configuration
WINDOW_LOCK_ENABLED = {window_lock_enabled}
WINDOW_STATE_PATH = {window_state_path}

# Deactivation phrases that return to sleeping state
DEACTIVATION_PHRASES = ("stop listening", "go to sleep", "never mind", "nevermind")

# Voice registration phrases (e.g. "register window two")
REGISTER_PREFIXES = ("register window",)

# Lookback buffer for split multi-word triggers
_last_chunk = ""

# Active window ID for current session (set from wake state slot)
_active_window_id = None


def _xdotool_key(key: str) -> None:
    """Send a keystroke via xdotool (to focused window)."""
    subprocess.Popen(["xdotool", "key", key], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def _xdotool_key_to_window(wid: int, key: str) -> None:
    """Send a keystroke to a specific window."""
    subprocess.Popen(
        ["xdotool", "key", "--window", str(wid), key],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


def _xdotool_type_to_window(wid: int, text: str) -> None:
    """Type text into a specific window."""
    subprocess.Popen(
        ["xdotool", "type", "--clearmodifiers", "--window", str(wid), text],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


def _xdotool_type_and_enter(digit: str) -> None:
    """Type a digit then press Enter via xdotool."""
    subprocess.Popen(
        ["xdotool", "type", "--clearmodifiers", digit],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    time.sleep(0.05)
    subprocess.Popen(["xdotool", "key", "Return"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def _window_exists(wid: int) -> bool:
    """Check if an X11 window still exists."""
    try:
        subprocess.check_output(
            ["xdotool", "getwindowname", str(wid)],
            stderr=subprocess.DEVNULL, timeout=2,
        )
        return True
    except (FileNotFoundError, subprocess.CalledProcessError, subprocess.TimeoutExpired):
        return False


def _get_active_window() -> tuple:
    """Get the currently focused window (id, title)."""
    try:
        wid = int(subprocess.check_output(
            ["xdotool", "getactivewindow"],
            stderr=subprocess.DEVNULL, timeout=2,
        ).decode().strip())
        title = subprocess.check_output(
            ["xdotool", "getwindowname", str(wid)],
            stderr=subprocess.DEVNULL, timeout=2,
        ).decode().strip()
        return wid, title
    except Exception:
        return None, ""


def _read_window_state() -> dict:
    """Read window registrations from windows.json."""
    try:
        with open(WINDOW_STATE_PATH, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {{"windows": {{}}, "default_slot": "1"}}


def _write_window_state(state: dict) -> None:
    """Write window state atomically."""
    tmp_path = WINDOW_STATE_PATH + ".tmp"
    try:
        os.makedirs(os.path.dirname(WINDOW_STATE_PATH), exist_ok=True)
        with open(tmp_path, "w") as f:
            json.dump(state, f)
        os.rename(tmp_path, WINDOW_STATE_PATH)
    except OSError:
        pass


def _send_key(key: str) -> None:
    """Send a keystroke — to locked window if active, else focused window."""
    if _active_window_id and _window_exists(_active_window_id):
        _xdotool_key_to_window(_active_window_id, key)
    else:
        _xdotool_key(key)


def _send_type(text: str) -> str:
    """Type text — to locked window if active (returns ""), else return text for nerd-dictation."""
    if _active_window_id:
        if _window_exists(_active_window_id):
            _xdotool_type_to_window(_active_window_id, text)
            return ""
        else:
            # Window gone — remove from state, fall through
            _remove_dead_window(_active_window_id)
    return text


def _remove_dead_window(wid: int) -> None:
    """Remove a dead window from state."""
    state = _read_window_state()
    windows = state.get("windows", {{}})
    to_remove = [slot for slot, w in windows.items() if w.get("window_id") == wid]
    for slot in to_remove:
        del windows[slot]
    if to_remove:
        _write_window_state(state)


def _resolve_window_id(slot: str) -> int | None:
    """Look up window ID for a slot from windows.json."""
    if not WINDOW_LOCK_ENABLED:
        return None
    state = _read_window_state()
    windows = state.get("windows", {{}})
    entry = windows.get(slot)
    if entry:
        wid = entry.get("window_id")
        if wid and _window_exists(wid):
            return wid
        # Dead window — clean up
        del windows[slot]
        _write_window_state(state)
    return None


def _read_wake_state() -> dict:
    """Read the wake word state file. Returns dict with state and activated_at."""
    try:
        with open(WAKEWORD_STATE_PATH, "r") as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return {{"state": "sleeping", "activated_at": 0.0}}


def _write_wake_state(state: str, activated_at: float = 0.0, persona: str = "", slot: str = "") -> None:
    """Write wake word state atomically via tmp+rename."""
    data = {{"state": state, "activated_at": activated_at}}
    if persona:
        data["persona"] = persona
    if slot:
        data["slot"] = slot
    tmp_path = WAKEWORD_STATE_PATH + ".tmp"
    try:
        os.makedirs(os.path.dirname(WAKEWORD_STATE_PATH), exist_ok=True)
        with open(tmp_path, "w") as f:
            json.dump(data, f)
        os.rename(tmp_path, WAKEWORD_STATE_PATH)
    except OSError:
        pass


def _check_trigger(text: str) -> tuple:
    """Check if text starts with a trigger word.

    Returns (remainder_text, persona_name, slot) if trigger found, else ("", "", "").
    Trigger must appear at the START of the text (or start of the combined
    lookback + current chunk) to avoid false activations from common words
    like "system" appearing mid-sentence.
    Slot is parsed from number word after trigger: "jarvis two" → slot "2".
    Uses _last_chunk for lookback on multi-word triggers split across chunks.
    """
    global _last_chunk
    lower = text.strip().lower()

    for trigger, persona in TRIGGER_WORDS.items():
        trigger_lower = trigger.lower()
        found = False
        remainder = ""

        # Direct match: trigger at start of current chunk
        if lower.startswith(trigger_lower):
            remainder = text.strip()[len(trigger_lower):].strip()
            found = True
        # Lookback: trigger split across previous + current chunk (at start)
        elif _last_chunk:
            combined = (_last_chunk + " " + lower).strip()
            if combined.startswith(trigger_lower):
                remainder = combined[len(trigger_lower):].strip()
                found = True

        if found:
            # Parse slot number from first word of remainder
            slot = "1"
            rem_words = remainder.lower().split() if remainder else []
            if rem_words and rem_words[0] in NUMBER_WORDS:
                slot = NUMBER_WORDS[rem_words[0]]
                remainder = " ".join(remainder.split()[1:]).strip()
            elif rem_words and rem_words[0].isdigit():
                slot = rem_words[0]
                remainder = " ".join(remainder.split()[1:]).strip()

            return remainder, persona, slot

    return "", "", ""


def _handle_voice_registration(lower: str) -> bool:
    """Handle 'register window [N]' voice commands. Returns True if handled."""
    for prefix in REGISTER_PREFIXES:
        if lower.startswith(prefix):
            rest = lower[len(prefix):].strip()
            slot = "1"
            if rest in NUMBER_WORDS:
                slot = NUMBER_WORDS[rest]
            elif rest.isdigit():
                slot = rest

            wid, title = _get_active_window()
            if wid:
                state = _read_window_state()
                state.setdefault("windows", {{}})[slot] = {{
                    "window_id": wid,
                    "title": title,
                }}
                _write_window_state(state)
            return True
    return False


def nerd_dictation_process(text: str) -> str:
    """Process text from nerd-dictation before typing.

    Called by nerd-dictation with each recognized text chunk.
    Return the text to type, or empty string to suppress typing.
    """
    global _last_chunk, _active_window_id
    lower = text.strip().lower()
    words = lower.split()

    # --- Wake word gate ---
    if WAKEWORD_ENABLED and TRIGGER_WORDS:
        state = _read_wake_state()
        now = time.time()

        if state.get("state") == "awake":
            activated_at = state.get("activated_at", 0.0)

            # Resolve window lock from wake state slot
            wake_slot = state.get("slot", "1")
            _active_window_id = _resolve_window_id(wake_slot)

            # Check timeout
            if DEACTIVATION_TIMEOUT > 0 and (now - activated_at) > DEACTIVATION_TIMEOUT:
                _write_wake_state("sleeping")
                _active_window_id = None
                _last_chunk = lower
                return ""

            # Refresh activation timestamp
            _write_wake_state("awake", now, state.get("persona", ""), wake_slot)

            # Handle voice registration commands
            if _handle_voice_registration(lower):
                return ""

            # Check deactivation phrases
            for phrase in DEACTIVATION_PHRASES:
                if phrase in lower:
                    _write_wake_state("sleeping")
                    _last_chunk = ""
                    _active_window_id = None
                    # "submit" + sleep on deactivation
                    if "submit" in lower:
                        _send_key("Return")
                    return ""

            # Fall through to normal keyword/option processing below

        else:
            # Sleeping: scan for trigger word
            remainder, persona, slot = _check_trigger(text)
            if remainder or persona:
                _write_wake_state("awake", now, persona, slot)
                _active_window_id = _resolve_window_id(slot)
                _last_chunk = ""
                if remainder:
                    # Process the remainder through normal flow
                    text = remainder
                    lower = text.strip().lower()
                    words = lower.split()
                else:
                    return ""
            else:
                _last_chunk = lower
                return ""  # Suppress — still sleeping

    else:
        # No wake word — resolve window from default slot if window lock enabled
        if WINDOW_LOCK_ENABLED:
            _active_window_id = _resolve_window_id("1")
        else:
            _active_window_id = None

    # --- Normal processing (no wake word, or awake) ---

    # Single-word keyword check
    if len(words) == 1 and lower in KEYWORDS:
        _send_key(KEYWORDS[lower])
        # "submit"/"enter" while wake word is active → send Enter + go back to sleeping
        if WAKEWORD_ENABLED and KEYWORDS[lower] == "Return":
            _write_wake_state("sleeping")
            _active_window_id = None
            _last_chunk = ""
        return ""

    # Two-word option selection: "select 2", "option three", etc.
    if len(words) == 2 and words[0] in OPTION_PREFIXES:
        digit = words[1]
        # Try direct digit
        if digit.isdigit():
            if _active_window_id and _window_exists(_active_window_id):
                _xdotool_type_to_window(_active_window_id, digit)
                time.sleep(0.05)
                _xdotool_key_to_window(_active_window_id, "Return")
            else:
                _xdotool_type_and_enter(digit)
            return ""
        # Try number word
        if digit in NUMBER_WORDS:
            d = NUMBER_WORDS[digit]
            if _active_window_id and _window_exists(_active_window_id):
                _xdotool_type_to_window(_active_window_id, d)
                time.sleep(0.05)
                _xdotool_key_to_window(_active_window_id, "Return")
            else:
                _xdotool_type_and_enter(d)
            return ""

    _last_chunk = lower
    return _send_type(text)
'''

NUMBER_WORDS = {
    "one": "1", "two": "2", "three": "3", "four": "4", "five": "5",
    "six": "6", "seven": "7", "eight": "8", "nine": "9", "ten": "10",
}


def generate_callback(config: Config | None = None) -> Path:
    """Generate the nerd-dictation callback script from current config.

    Returns the path to the generated script.
    """
    cfg = config or Config.load()
    keywords = cfg.dictation.keywords

    # Build inverted trigger_words: trigger phrase → persona name
    trigger_words = {}
    for persona, trigger in cfg.rephrase.trigger_words.items():
        if trigger.strip():
            trigger_words[trigger.strip().lower()] = persona

    from claudible.paths import WAKEWORD_STATE, WINDOW_STATE

    CALLBACK_DIR.mkdir(parents=True, exist_ok=True)

    script = _TEMPLATE.format(
        keywords_dict=repr(keywords),
        number_words_dict=repr(NUMBER_WORDS),
        wakeword_enabled=repr(cfg.stt.wakeword_enabled),
        trigger_words_dict=repr(trigger_words),
        deactivation_timeout=repr(cfg.stt.wakeword_timeout),
        wakeword_state_path=repr(str(WAKEWORD_STATE)),
        window_lock_enabled=repr(cfg.stt.window_lock_enabled),
        window_state_path=repr(str(WINDOW_STATE)),
    )

    CALLBACK_FILE.write_text(script, encoding="utf-8")
    log.info("Generated nerd-dictation callback: %s", CALLBACK_FILE)
    return CALLBACK_FILE


def remove_callback() -> None:
    """Delete the generated callback script."""
    if CALLBACK_FILE.exists():
        CALLBACK_FILE.unlink()
        log.info("Removed nerd-dictation callback: %s", CALLBACK_FILE)
